name: Run tests
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create cache venv
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3.8 -m venv i./.venv && . ./.venv/bin/activate &&
          pip install -r requirements.txt && python setup.py install

      - name: Unit test
        run: . ./.venv/bin/activate && pytest -v --cov=aiaccel --cov-branch --cov-report=term-missing tests/unit

      - name: Pycodestyle
        run: . ./.venv/bin/activate && pytest -v --pycodestyle aiaccel examples

      - name: Flack8
        run: . ./.venv/bin/activate && pytest -v --flake8 aiaccel examples