name: Run tests
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python3.8
        uses: actions/setup-python@v2
          with:
            python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV