name: Tests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create cache venv
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - name: Install dependencies
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python3.8 -m venv .venv && . ./.venv/bin/activate &&
          pip install -r requirements.txt && python setup.py install
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Unit test
        run: . ./.venv/bin/activate && pytest -v --cov=aiaccel --cov-branch --cov-report=term-missing tests/unit

      - name: Pycodestyle
        run: . ./.venv/bin/activate && pytest -v --pycodestyle aiaccel examples

      - name: Flack8
        run: . ./.venv/bin/activate && pytest -v --flake8 aiaccel examples