name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-20.04]
        #python-version: ['3.8', '3.9', '3.10']
        python-version: ['3.8']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Software
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install

      - name: Unit Test
        run: |
          pytest -v --cov=aiaccel --cov-branch --cov-report=term-missing tests/unit/test_buffer.py
          pwd
          ls
          ls /home/runner
          ls /home/runner/work
          ls /home/runner/work/aiaccel-dev
          ls /home/runner/work/aiaccel-dev/aiaccel-dev
          ls /home/runner/work/aiaccel-dev/aiaccel-dev/tests
          ls /home/runner/work/aiaccel-dev/aiaccel-dev/tests/test_data
          ls /home/runner/work/aiaccel-dev/aiaccel-dev/tests/test_data/work
          ls /home/runner/work/aiaccel-dev/aiaccel-dev/tests/test_data/work/state
          pytest -v --cov=aiaccel --cov-branch --cov-report=term-missing tests/unit/test_common.py
